#spring.application.name=memo_app

#spring:
#  application:
#    name: memo_app
#  datasource:
#    url: jdbc:postgresql://:5432/memo_app
#    username: memo_app
#    password: password


spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}